/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Server } from "./Server";
import { ServerCountArgs } from "./ServerCountArgs";
import { ServerFindManyArgs } from "./ServerFindManyArgs";
import { ServerFindUniqueArgs } from "./ServerFindUniqueArgs";
import { DeleteServerArgs } from "./DeleteServerArgs";
import { ServerService } from "../server.service";
@graphql.Resolver(() => Server)
export class ServerResolverBase {
  constructor(protected readonly service: ServerService) {}

  async _serversMeta(
    @graphql.Args() args: ServerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Server])
  async servers(@graphql.Args() args: ServerFindManyArgs): Promise<Server[]> {
    return this.service.servers(args);
  }

  @graphql.Query(() => Server, { nullable: true })
  async server(
    @graphql.Args() args: ServerFindUniqueArgs
  ): Promise<Server | null> {
    const result = await this.service.server(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Server)
  async deleteServer(
    @graphql.Args() args: DeleteServerArgs
  ): Promise<Server | null> {
    try {
      return await this.service.deleteServer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
